In [ ]:
# a) (5 Points) Find the eigenvalues and eigenvectors of 𝐴.
# b) (5 Points) Diagonalize 𝐴 using 𝐴 = 𝑄𝛬𝑄−1.
# c) (5 Points) Use Python to verify that 𝐴 = 𝑄𝛬𝑄−1.
# d) (5 Points) Compute A3 using 𝑄𝛬3𝑄−1

In [2]:
# Matrix A
import numpy as np
A = np.array([[2, 0], [0, 5]])

print(A)

[[2 0]
 [0 5]]


In [6]:
# Part a
# Eigenvalues of A are the diagonal since A is already diaganol matrix

eigen_values, eigen_vectors = np.linalg.eig(A)
print("Eigen Values: ", eigen_values)
print("Eigen Vectors: \n", eigen_vectors)



Eigen Values:  [2. 5.]
Eigen Vectors: 
 [[1. 0.]
 [0. 1.]]


In [11]:
# Part b - Diagonalize 𝐴 using 𝐴 = 𝑄𝛬𝑄−1.

Q = eigen_vectors
Lambda = np.array([[eigen_values[0], 0], [0, eigen_values[1]]])
Q_inverse =  np.linalg.inv(Q)

print("Q: \n", Q)
print("Lambda: \n", Lambda)
print("Q_inverse: \n", Q_inverse)

Q: 
 [[1. 0.]
 [0. 1.]]
Lambda: 
 [[2. 0.]
 [0. 5.]]
Q_inverse: 
 [[1. 0.]
 [0. 1.]]


In [14]:
# Part c - Verify

A = Q @ Lambda @ Q_inverse
print("A = 𝑄𝛬3𝑄−1: \n", A)


A = 𝑄𝛬3𝑄−1: 
 [[2. 0.]
 [0. 5.]]


In [15]:
# Part d - Compute A3 using 𝑄𝛬3𝑄−1
# QQ-1 = I, so A3 = 𝛬3

A3 = Lambda @ Lambda @ Lambda
print("A3 using 𝑄𝛬3𝑄−1: \n", A3)
print("A3 (A * A * A): \n", A @ A @ A)

A3 using 𝑄𝛬3𝑄−1: 
 [[  8.   0.]
 [  0. 125.]]
A3 (A * A * A): 
 [[  8.   0.]
 [  0. 125.]]
